# Define Network
networks:
  jenkins_network:
    name: jenkins_network
    driver: bridge

# Define Services
services:
  jenkins:
    build: .
    image: jenkins-with-docker:jdk21
    container_name: jenkins
    user: root # Run as root to allow entrypoint script to set permissions
    volumes:
      - ./jenkins_home:/var/jenkins_home # Persist Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock # Allow Docker-in-Docker
    environment:
      - JENKINS_OPTS=--httpPort=8800 # Jenkins UI port
    ports:
      - "8800:8800" # Jenkins UI
      - "50000:50000" # Jenkins agent port
    restart: always
    networks:
      - jenkins_network
